# Use the official Jenkins agent image as the base
FROM jenkins/inbound-agent:latest

# Switch to root for installation tasks
USER root

# Install necessary dependencies
RUN apt-get update && apt-get install -y git maven ca-certificates curl gnupg2

# Install Docker for the Jenkins container
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io

# Add the Jenkins user to the Docker group
RUN usermod -aG docker jenkins

# Switch back to the Jenkins user
USER jenkins